# Generated by Django 6.0.5 on 2026-05-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Commune',
            },
        ),
        migrations.CreateModel(
            name='Poubelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('etat', models.CharField(choices=[('vide', 'Vide'), ('pleine', 'Pleine'), ('endommagee', 'Endommagée')], default='vide', max_length=20)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalements.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('poubelle_pleine', 'Poubelle pleine'), ('depot_sauvage', 'Dépôt sauvage'), ('retard_collecte', 'Retard de collecte'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('pris_en_charge', 'Pris en charge'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('citoyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.commune')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
