# Generated by Django 6.0.5 on 2026-05-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_alter_signalement_citoyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.commune'),
        ),
    ]
